Naming/MethodParameterName:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
