Naming/MethodParameterName:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
